site_name: C3 Documentation
markdown_extensions:
  - footnotes
nav:
  - About C3: 'index.md'
  - Installing:
    - Setup: 'setup.md'
    - Your first project: 'firstproject.md'
    - A quick primer on C3: 'primer.md'
    - Feature list: 'allfeatures.md'
  - Documentation:
    - Changes from C: 'changesfromc.md'
    - Comparisons with other languages: 'compare.md'
    - Examples: 'examples.md'
    - Modules: 'modules.md'
    - Types: 'types.md'
    - Define: 'define.md'
    - Arrays: 'arrays.md'
    - Functions: 'functions.md'
    - Statements: 'statements.md'
    - Expressions: 'expressions.md'
    - Variables: 'variables.md'
    - Optionals and error handling: 'optionals.md'
    - Compile time evaluation: 'compiletime.md'
    - Contracts: 'contracts.md'
    - Generics: 'generics.md'
    - Macros: 'macros.md'
    - Reflection: 'reflection.md'
    - Operator overloading: 'operators.md'
    - Any and protocols: 'anyprotocols.md'
    - Undefined behaviour: 'undefinedbehaviour.md'
    - Conversions: 'conversion.md'
    - Precedence: 'precedence.md'
    - Builtins: 'builtins.md'
    - Libraries: 'libraries.md'
    - Standard Library: 'standard_library.md'
    - More ideas: 'ideas.md'
    - Naming rules: 'naming.md'
    - Comments & Docs: 'comments.md'
    - Attributes: 'attributes.md'
    - Inline asm: 'asm.md'
    - C Interop: 'cinterop.md'
    - Grammar: 'syntax.md'
    - More code examples: 'sample.md'
    - Specification: 'specification.md'
  - Build system:    
    - Introduction: 'buildintro.md'
    - Project Structure: 'project.md'
    - Commands: 'buildcommands.md'
  - Development:
    - Contribute: 'contribute.md'  
    - Changes: 'changes.md'
    - Rejected ideas: 'rejectedideas.md'
theme:
    name: readthedocs
    hljs_languages:
            - yaml
            - rust
            - ebnf
            - bnf
dev_addr: 192.168.1.4:8000
